# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "helm"
    directory: "/charts/wordpress"
    schedule:
      interval: "weekly"
    ignore:
      # Ignore container images in values.yaml, but allow Chart.yaml dependencies
      - dependency-name: "docker.io/wordpress"
      - dependency-name: "docker.io/mariadb"
      - dependency-name: "docker.io/memcached"
      - dependency-name: "lusotycoon/apache-exporter"
  - package-ecosystem: "helm"
    directory: "/charts/wg-easy"
    schedule:
      interval: "weekly"
