{{- if and (empty .Values.wireguard.existingSecret) (.Values.wireguard.client.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wireguard.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ include "wireguard.fullname" . }}
type: Opaque
stringData:
  wg0.conf: |
    [Interface]
    {{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.wireguard.client.config.existingSecret -}}
    {{- if $secret }}
    {{- $privatekey := default "" $secret.data.interfacePrivateKey }}
    PrivateKey = {{ $privatekey | b64dec }}
    {{- else }}
    PrivateKey = 
    {{- end }}
    Address = {{ .Values.wireguard.client.config.address }}
    DNS = {{- if .Values.wireguard.dns }} {{ .Values.wireguard.dns }} {{- else }} 1.1.1.1, 2606:4700:4700::1111 {{- end }}
    MTU = {{- if .Values.wireguard.client.config.mtu }} {{ .Values.wireguard.client.config.mtu }} {{- else }} 1420 {{- end }}

    [Peer]
    {{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.wireguard.client.config.existingSecret -}}
    {{- if $secret }}
    {{- $publickey := default "" $secret.data.peerPublicKey }}
      PublicKey = {{ $publickey | b64dec }}
    {{- else }}
      PublicKey = 
    {{- end }}
    {{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.wireguard.client.config.existingSecret -}}
    {{- if $secret }}
    {{- $presharedkey := default "" $secret.data.peerPresharedKey }}
      PresharedKey = {{ $presharedkey | b64dec }}
    {{- else }}
      PresharedKey = 
    {{- end }}
    AllowedIPs = {{- if .Values.wireguard.allowedIPs }} {{ .Values.wireguard.allowedIPs }} {{- else }} 0.0.0.0/0, ::0/0 {{- end }}
    PersistentKeepAlive = {{- if .Values.wireguard.client.config.persistentKeepalive }} {{ .Values.wireguard.client.config.persistentKeepalive }} {{- else }} 25 {{- end }}
    Endpoint =  {{ .Values.wireguard.client.config.endpoint }}
{{- end }}