apiVersion: v2
name: wordpress
description: "Using the official WordPress image. This chart provides automation for installation, user management, plugin installation, and metrics."
type: application
version: 0.2.6
appVersion: "6.8.2"
icon: https://raw.githubusercontent.com/slydlake/helm-charts/refs/heads/main/charts/wordpress/app.png
home: https://github.com/slydlake/helm-charts
maintainers:
  - name: slydlake
sources:
  - https://github.com/slydlake/helm-charts
annotations:
  artifacthub.io/category: networking
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: SlyCharts GitHub Repository
      url: https://github.com/slydlake/helm-charts/tree/main/charts/wordpress
    - name: Official WordPress Repository
      url: https://github.com/docker-library/
    - name: "WordPress Prometheus Metrics plugin - SlyMetrics"
      url: https://github.com/slydlake/slymetrics
    - name: Apache Metrics container
      url: https://github.com/Lusitaniae/apache_exporter
  artifacthub.io/maintainers: |
    - name: slydlake
      email: sly.dlake@gmail.com
  artifacthub.io/changes: |
    - kind: added
      description: "Wordpress CLI image version can now be set"
    - kind: added
      description: "Detailed comments for all values"
    - kind: changed
      description: "Pinned all images to specific tags and digests to improve security"
    - kind: changed
      description: "Pinned chart dependencies to specific versions"
    - kind: changed
      description: "ImagePullPolicy for all images set to IfNotPresent"
  artifacthub.io/containsSecurityUpdates: false
  artifacthub.io/images: |
    - name: wordpress
      image: docker.io/wordpress:6.8.2-php8.1-apache
    - name: wordpress-cli
      image: docker.io/wordpress:cli-2.12.0-php8.1
    - name: metrics-apache
      image: lusotycoon/apache-exporter:v1.0.10
    - name: mariadb
      image: docker.io/mariadb:12.0.2-noble
    - name: memcached
      image: docker.io/memcached:1.6.39
dependencies:
  - condition: memcached.enabled
    name: memcached
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.1.3
  - condition: mariadb.enabled
    name: mariadb
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.2.7
keywords:
  - wordpress
  - blog
