apiVersion: v2
name: wireguard
description: "Using the offical linuxserver/wireguard image with almost any environment variables for K8S. Supporting server and client mode."
type: application
version: 0.1.14
icon: https://raw.githubusercontent.com/slydlake/helm-charts/refs/heads/main/charts/wireguard/app.png
home: https://github.com/slydlake/helm-charts
maintainers:
  - name: slydlake
sources:
  - https://github.com/slydlake/helm-charts
annotations:
  artifacthub.io/category: security
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: SlyCharts GitHub Repository
      url: https://github.com/slydlake/helm-charts/tree/main/charts/wireguard
    - name: Offical WireGuard Repository
      url: https://github.com/linuxserver/docker-wireguard
  artifacthub.io/maintainers: |
    - name: slydlake
      email: sly.dlake@gmail.com
  artifacthub.io/changes: |
    - kind: added
      description: "LoadBalancer service type support"
    - kind: added
      description: "externalIPs in values.yaml"
  artifacthub.io/containsSecurityUpdates: false
  artifacthub.io/images: |
    - name: wireguard
      image: docker.io/linuxserver/wireguard:latest
keywords:
  - wireguard
  - vpn
  - linuxserver
